### ISSUE TITLE
Unable to change more than one ch up and down

### ISSUE THREAD

**Issue by norwayRP** [trclassic92/qb-radio#1]
Hi

When trying to change from ch 8, pressing next will give you ch9 and prev wil give you ch 7
Not possible to scroll true channels as it seams to be what suppose to do.

**Comment by trclassic92** [comment]
If you are referring to when you hit the arrows to go to a new channel you can only move up by one channel. The easiest way to switch channels is to just type in the new channel you would like to join or use the radial menu for easier access to switch between channels.
