### ISSUE TITLE
Others can not hear me unless I have radio out and visible on my screen

### ISSUE THREAD

**Issue by ksduster** [trclassic92/qb-radio#2]
Other players can only hear me if the radio is out and visible.

If it is not out they can hear mic clicks, but no voice audio.

**Comment by ksduster** [comment]
That is fine to mark this as invalid.
There is a collision with the default mappings between pma-voice, qb-target, and qb-menu.
Using L-alt is a poor choice by default due to this.
Change the pma-voice to CapsLock, works like a champ.

**Comment by trclassic92** [comment]
This has nothing to do with this radio as this is just the default qb-radio with a ui change

Also this was marked as invaild because you had no detail about what the issue was.
